version: '3'

services:
  # RabbitMQ - Kuyruklama sistemi
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"  # AMQP protokolü
      - "15673:15672"  # Yönetim arayüzü
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped
  
  # MongoDB - Veritabanı (verilerin zaman serisi olarak saklanması için)
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=air_quality_db
    restart: unless-stopped
    
  # Backend - FastAPI uygulaması
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/air_quality_db?authSource=admin
      - MONGODB_DB_NAME=air_quality_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
      - RABBITMQ_VHOST=/
      - DEBUG=true
    restart: on-failure:3

volumes:
  rabbitmq-data:
  mongodb-data: 