version: '3'

services:
  # RabbitMQ - Kuyruklama sistemi
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"  # AMQP protokolü
      - "15673:15672"  # Yönetim arayüzü
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  rabbitmq-data: 